In [2]:
import numpy as np

In [3]:
inputs = [[1.0, 2.0, 3.1 , 2.3],  # these are called Batch(es)
          [1.1, 2.2, 3.2 , 2.5],
          [1.3, 2.3, 3.4 , 2.6]]

weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.1, 0.7, -0.4, 1.1], 
           [0.4, 1.0, -0.7, 1.3]]

biases = [2, 2.5, 1.2]

In [4]:
print(np.shape(inputs))
print(np.shape(weights))
print(np.shape(weights)[1])

(3, 4)
(3, 4)
4


In [5]:
print(np.array(weights).T)
print(np.shape(np.array(weights).T))

[[ 0.2  0.1  0.4]
 [ 0.8  0.7  1. ]
 [-0.5 -0.4 -0.7]
 [ 1.   1.1  1.3]]
(4, 3)


In [6]:
output = np.dot(inputs, np.array(weights).T) + biases
print(output) # (3, 4).(4, 3) = (3, 3)

[[4.55 5.29 4.42]
 [4.88 5.62 4.85]
 [5.   5.74 5.02]]


Making multi layer output

In [7]:
np.random.seed(0)

In [8]:
class Layer_Denser:
    def __init__(self, n_inputs, n_neurons):
        self.weight = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forware(self, inputs):
        self.output = np.dot(inputs, self.weight) + self.biases
        # no need of return

In [9]:
layer1 = Layer_Denser(4, 2) # init class
layer2 = Layer_Denser(2, 5) # layer1[output] = layer2[input]


In [10]:
layer1.forware(inputs)
print(layer1.output) # (3, 4).(4, 2) = (3, 2)

[[1.16961614 0.15042606]
 [1.24450878 0.18644557]
 [1.33642925 0.19579852]]


In [11]:
layer2.forware(layer1.output)
print(layer2.output) # (3, 5)

[[-0.01024233  0.05470112  0.0218669   0.19256902  0.08592609]
 [-0.0105771   0.05937498  0.02414756  0.20884206  0.09088673]
 [-0.01141209  0.06356436  0.0257837   0.22360721  0.09769034]]


In [12]:
layer3 = Layer_Denser(5, 2) # init class
layer3.forware(layer2.output)
print(layer3.output) # (3, 2)

[[ 0.03170609 -0.0267877 ]
 [ 0.0344158  -0.02908243]
 [ 0.03684401 -0.03113346]]
