In [3]:
tryout1 = [1, -2, 3 , -4, 5, -6, -7]

In [8]:
output_try1 = []
for j in tryout1:
    if j > 0:
        output_try1.append(j)
    elif j <= 0:
        output_try1.append(0)

print(output_try1)

[1, 0, 3, 0, 5, 0, 0]


In [7]:
output_try1 = []
for i in tryout1: # Activation Function ReLU
    output_try1.append(max(0, i)) # Rectifier Linear Unit

print(output_try1)

[1, 0, 3, 0, 5, 0, 0]


In [13]:
import numpy as np
np.random.seed(0)

In [9]:
X = [[1.0, 2.0, 3.1 , 2.3],  # inputs/feature set
     [1.1, 2.2, 3.2 , 2.5],
     [1.3, 2.3, 3.4 , 2.6]]

weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.1, 0.7, -0.4, 1.1], 
           [0.4, 1.0, -0.7, 1.3]]

biases = [2, 2.5, 1.2]

In [14]:
class Layer_Denser:
    def __init__(self, n_inputs, n_neurons):
        self.weight = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forware(self, inputs):
        self.output = np.dot(inputs, self.weight) + self.biases
        # no need of return

In [22]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [17]:
layer1 = Layer_Denser(4, 2) # init class
layer1.forware(X)

layer2 = Layer_Denser(2, 5)
layer2.forware(layer1.output)

layer3 = Layer_Denser(5, 4) # init class
layer3.forware(layer2.output) # many negative values
print(layer3.output) # (3, 4) 

[[ 2.54875561e-02 -3.32654227e-02  7.67333084e-03  4.49973505e-05]
 [ 2.71653809e-02 -3.55988821e-02  7.64804028e-03 -7.19300128e-04]
 [ 2.86212605e-02 -3.75362137e-02  7.94907356e-03 -9.15302301e-04]]


In [23]:
active1 = Activation_ReLU() # init class
active1.forward(layer3.output)
print(active1.output)
# negative values => zeros now

[[2.54875561e-02 0.00000000e+00 7.67333084e-03 4.49973505e-05]
 [2.71653809e-02 0.00000000e+00 7.64804028e-03 0.00000000e+00]
 [2.86212605e-02 0.00000000e+00 7.94907356e-03 0.00000000e+00]]
