In [1]:
import numpy as np
np.random.seed(0)

In [2]:
X = [[1.0, 2.0, 3.1 , 2.3],  # inputs/feature set
     [1.1, 2.2, 3.2 , 2.5],
     [1.3, 2.3, 3.4 , 2.6]]

weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.1, 0.7, -0.4, 1.1], 
           [0.4, 1.0, -0.7, 1.3]]

biases = [2, 2.5, 1.2]

In [7]:
class Layer_Denser:
    def __init__(self, n_inputs, n_neurons):
        self.weight = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weight) + self.biases
        # no need of return

In [4]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [5]:
class Softmax_activation:
    def forward(self, inputs):
        expo_val = np.exp(inputs - np.max(inputs))
        # norm_base = np.sum(expo_values, axis=1, keepdims=True)
        proba = expo_val/np.sum(expo_val, axis=1, keepdims=True)
        self.output = proba # probabilities

In [8]:
dense1 = Layer_Denser(4, 2)
dense1.forward(X)

activ1 = Activation_ReLU()
activ1.forward(dense1.output)

In [13]:
dense2 = Layer_Denser(2, 3)
dense2.forward(activ1.output)

activ2 = Softmax_activation()
activ2.forward(dense2.output)

In [14]:
print(activ2.output) # nearly equal probabilities
# the more they run, the more accurate they will get

[[0.32497341 0.32790251 0.34712408]
 [0.32412076 0.32783057 0.34804867]
 [0.3235638  0.32758903 0.34884717]]
