In [ ]:
# Input -> Exponentiate -> Normalize -> Output
# Softmax Function == Exponentiate + Normalize

In [4]:
import math # just for understanding
exponential_math = math.e
print(exponential_math) # e == 2.718281828459045

2.718281828459045


In [16]:
import numpy as np

In [11]:
layer_outputs = [[3.1, 4.3, -2.4],
                 [-2, -1, 4.5], # another way to deal with negatives
                 [-1.8, -0.9, 0.1]] 
simple_layer = [-1.8, -0.9, 0.1]

In [14]:
# Exponential function
exponential_values = []
for j in simple_layer: # e**n (e power n)
    exponential_values.append(exponential_math**j)

print(exponential_values)

[0.16529888822158656, 0.4065696597405991, 1.1051709180756477]


In [18]:
# power of numpy ... No more need of math.e (export math)
expo_values = np.exp(layer_outputs)
print(expo_values) # no more negatives to deal with (without losing them)

[[22.19795128 73.6997937   0.09071795]
 [ 0.13533528  0.36787944 90.0171313 ]
 [ 0.16529889  0.40656966  1.10517092]]


In [25]:
# Normalization ... for example -1.8/(-1.8 + -0.9 + 0.1)
# this keeps the value between 0 and 1

norm_base = sum(exponential_values)
norm_values = []

for k in exponential_values:
    norm_values.append(k/norm_base)

print(norm_values)
print("base values:", norm_base)

[0.09856589040931818, 0.2424329707047139, 0.6590011388859679]
base values: 1.6770394660378334


In [26]:
norm_np_base = np.sum(expo_values, axis=1, keepdims=True) # axis == 1(horizontal)
print(norm_np_base) # keepdims == keeps dimensions same

norm_np_values = expo_values/norm_np_base
print(norm_np_values)

[[95.98846293]
 [90.52034602]
 [ 1.67703947]]
[[2.31256451e-01 7.67798457e-01 9.45092259e-04]
 [1.49508137e-03 4.06405253e-03 9.94440866e-01]
 [9.85658904e-02 2.42432971e-01 6.59001139e-01]]


In [29]:
# Exponential function also has an issue
# it can't take big values like 1000 
# sol: subtract all values with biggest value and make them negative

new_expo_values = np.exp(layer_outputs - np.max(layer_outputs))
print(new_expo_values) 

[[0.24659696 0.81873075 0.00100779]
 [0.00150344 0.00408677 1.        ]
 [0.0018363  0.00451658 0.01227734]]


In [30]:
norm_np_base = np.sum(new_expo_values, axis=1, keepdims=True) 
print(norm_np_base) # keepdims == keeps dimensions same

norm_np_values = new_expo_values/norm_np_base
print(norm_np_values) # YES!! Same values

[[1.0663355 ]
 [1.00559021]
 [0.01863023]]
[[2.31256451e-01 7.67798457e-01 9.45092259e-04]
 [1.49508137e-03 4.06405253e-03 9.94440866e-01]
 [9.85658904e-02 2.42432971e-01 6.59001139e-01]]


In [ ]:
class Softmax_activation:
    def forward(self, inputs):
        expo_values = np.exp(inputs - np.max(inputs))
        # norm_base = np.sum(expo_values, axis=1, keepdims=True)
        proba = expo_values/np.sum(expo_values, axis=1, keepdims=True)
        self.output = proba # probabilities

In [ ]:
# we will use this in next part with our main code